[package]
name = "nrf52840dk-sample"
version = "0.1.0"
authors = ["Michael Nitschinger <michael@nitschinger.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
nrf52840-hal = "0.18"
embedded-hal = "1.0.0"
ssd1306 = { version = "0.10.0", features = ["graphics"] }
embedded-graphics = "0.8.1"

[profile.release]
opt-level = 2
