[package]
name = "hijo"
version = "0.1.0"
authors = ["Logan Michaels"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
nrf52840-hal = "0.18"
embedded-hal = "1.0.0"
ssd1306 = { version = "0.10.0", features = ["graphics"] }
embedded-graphics = "0.8.1"
heapless = "0.8.0"
nmea = { version = "0.7.0", default-features = false, features = ["GGA", "GLL"]}
nb = "1.1.0"

[profile.release]
opt-level = 1
